config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'content#index'

  get "angular_test", to: "angular_test#index"

  get 'content' => 'content#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/controllers/angular_test_controller.rb
class AngularTestController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/angular_test/index.html.erb
<article ng-app="angular_test">
  <header>
    <h1 ng-if="name">Hello, {{name}}</h1>
  </header>
  <section>
    <form class="form-inline">
      <div class="form-group">
        <label for="name">Name</label>
        <input class="form-control"
        name="name"
        type="text"
        placeholder="Enter your name"
        autofocus
        ng-model="name">
      </div>
    </form>
  </section>
</article>

app/views/home/index.html.erb
<html>
<head>
  <meta charset="utf-8">
  <title>BNHair</title>
  <script src="https://use.fontawesome.com/012e4d53dc.js"></script>

  <title>BNHair - Theme</title>

  <!-- Bootstrap Core CSS -->
  <link href="assets/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="assets/agency.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="assets/style.css" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="assets/font-awesome.min.css" rel="stylesheet" type="text/css">

  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>

    <!-- Header -->
    <header>
        <div class="container">
            <div class="intro-text">
                <div class="intro-lead-in">Welcome To BNHair Studio</div>
                <!-- <div class="intro-heading">It's Nice To Meet You</div> -->
                <!-- <button class="btn btn-default btn-xl"> -->
                <%= link_to 'Step Inside the BNHair Experience', content_path %></button>
            </div>
        </div>
    </div>
</header>

</html>

app/views/home/index1.html.erb
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-10">
        <center>
          <div class="outer">
            <div class="inner"><strong><h1 class="white_text">Welcome to BNHair</h1></strong></div>
          </div>
        </center>
      </div>
    </div>
  </div>

app/views/layouts/_footer_hero.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <br>
      <div class="col-md-4">
        <center>
          <img src="../../assets/images/facebook.png" class="img-circle" alt="Facebook">
          <br>
          <strong><h4 class="footertext">Facebook</h4></strong>
        </center>
      </div>
      <div class="col-md-4">
        <center>
          <img src="../../assets/images/instagram.png" class="img-circle" alt="Instagram">
          <br>
          <strong><h4 class="footertext">Instagram</h4></strong>
        </center>
      </div>
      <div class="col-md-4">
        <center>
          <img src="../../assets/images/twitter.png" class="img-circle" alt="Twitter">
          <br>
          <strong><h4 class="footertext">Twitter</h4></strong>
        </center>
      </div>
    </div>
    <div class="row">
      <p><center>
        <strong><p class="footertext">510-690-9655 * 22550 Main Street * Hayward, CA 94541</p></strong>
        <!-- <a href="#">Email@gmail.com</a> -->
        <img src="../../assets/images/mail.png" class="img-circle" alt="Twitter">
        <br>
        <strong><h4 class="footertext">Email</h4></strong>
        <br>
        <img src="../../assets/images/brittany_logo.png" alt="BNhair Studio">
        <br>
        <br>
        <br>
        <br>
        <strong><p class="footertext">Copyright 2016</p></strong>
      </center></p>
    </div>
  </div>
</div>

app/views/layouts/_navigation_bar.html.erb
<body class="box">

  <div class="container-fluid">
    <div class="row">
      <br>
      <div class="col-md-10">
        <div class="col-md-10 col-md-offset-4">
          <center>
           <p class="text-center">
            <ul class="nav nav-pills">
              <li role="presentation"><a href="#">HOME</a></li>
              <li role="presentation"><a href="#">OUR TEAM</a></li>
              <li role="presentation"><a href="#">BLOG</a></li>
              <li role="presentation"><a href="#">SERVICES & POLICIES</a></li>
              <li role="presentation"><a href="#">CONTACT</a></li>
            </ul>
          </p>
        </center>
      </div>
    </div>
  </div>
</div>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bnhair</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

  <%= yield %>


</body>
</html>